=== maximiliani/FDConcepts/Operation Type Profiles/schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "",
  "title": "FAIR Digital Operation Type Profiles",
  "description": "This schema describes the structure of a FAIR Digital Operation Type Profile. FAIR Digital Operation Type Profiles are used to describe the technology and attributes of a FAIR Digital Operation.",
  "type": "object",
  "required": [
    "pid",
    "name",
    "description",
    "createdAt",
    "license",
    "contributors",
    "attributes",
    "adapters"
  ],
  "properties": {
    "pid": {
      "title": "PID",
      "description": "A automatically generated persistent identifier referring to this operation type profile.",
      "type": "string"
    },
    "name": {
      "title": "Type Name",
      "description": "A human readable name for the operation type profile",
      "type": "string",
      "maxLength": 128
    },
    "description": {
      "title": "Description",
      "description": "A human readable description of the operation type profile",
      "type": "string",
      "maxLength": 2048,
      "pattern": "(.|\n)*"
    },
    "createdAt": {
      "title": "Creation date",
      "description": "The date when this operation type profile was created in RFC 3339 format.",
      "type": "string",
      "format": "datetime"
    },
    "lastModifiedAt": {
      "title": "Modification date",
      "description": "The date when this operation type profile was lastly modified in RFC 3339 format.",
      "type": "string",
      "format": "datetime"
    },
    "license": {
      "title": "License",
      "description": "The license of this operation type profile. It is a PID or URL pointing to a license.",
      "type": "string"
    },
    "contributors": {
      "title": "Contributors",
      "description": "Information about the creators/maintainers/contributors.",
      "type": "array",
      "items": {
        "title": "Provenance information",
        "description": "Information about a person, group, or organization.",
        "type": "object",
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "title": "Type of the provenance information",
            "description": "The type specifies the kind of reference to the subject. It can be a URL, a Handle, an ORCiD, or some plain text.",
            "type": "string",
            "enum": [
              "Handle",
              "ORCiD",
              "URL",
              "Text"
            ]
          },
          "url": {
            "title": "URL",
            "description": "A URL referring to a person, group, or organization. When ORCiD is chosen as a type, this refers to the ORCiD profile.",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "description": "The name of a person, group, or organization",
            "type": "string"
          },
          "email": {
            "title": "E-Mail address",
            "description": "An email address for a person, group, or organization",
            "type": "string"
          },
          "details": {
            "title": "Details",
            "type": "string",
            "format": "textarea",
            "maxLength": 1024
          }
        }
      }
    },
    "attributes": {
      "type": "array",
      "title": "Attributes",
      "description": "Definition of the attributes this operation type profile uses. The attributes are used to describe the input an operation uses to produce an output.",
      "items": {
        "title": "Attribute",
        "type": "object",
        "required": [
          "pid",
          "name"
        ],
        "properties": {
          "pid": {
            "title": "PID",
            "description": "PID referring to the data type or type profile this attribute uses",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "description": "Name assigned to this attribute",
            "type": "string",
            "maxLength": 256
          },
          "description": {
            "title": "Description",
            "description": "Description of how this data type/type profile is used in this context",
            "type": "string",
            "format": "textarea",
            "maxLength": 2048
          },
          "repeatable": {
            "title": "Repeatability",
            "description": "Cardinality of this property.",
            "type": "boolean",
            "default": false
          },
          "obligation": {
            "title": "Obligation",
            "description": "Describes if this property is optional or mandatory to be specified in the operation.",
            "type": "string",
            "enum": [
              "Optional",
              "Mandatory"
            ],
            "default": "Optional"
          },
          "defaultValue": {
            "title": "Default Value",
            "description": "A default value can be provided here. Needs to be a string representation of a JSON object that is compatible with these restrictions. String delimiters need to be escaped",
            "type": "string",
            "maxLength": 262144
          },
          "constantValue": {
            "title": "Constant Value",
            "description": "Used if the type has a constant value on all possible instances for this parameter. This value cannot be changed in the Operation. Needs to be a string representation of a JSON object that is compatible with these restrictions. String delimiters need to be escaped",
            "type": "string",
            "maxLength": 262144
          }
        }
      }
    },
    "adapters": {
      "title": "List of adapters",
      "description": "A list of adapters for the FAIR Digital Operation Type Profile. Adapters are used to provide the technology-specific implementation of a FAIR Digital Operation Type Profile.",
      "type": "array",
      "items": {
        "title": "Adapter",
        "description": "A reference to an adapter for the technical specification of a FAIR Digital Operation Type Profile.",
        "type": "string"
      }
    }
  }
}

=== maximiliani/FDConcepts/Operation Type Profiles/examples/http.json
{
  "$schema": "../schema.json",
  "pid": "PID->HTTPRequest",
  "name": "HTTP Request",
  "description": "This pattern is used to make a HTTP request to a server.",
  "createdAt": "2024-02-06T12:00:00Z",
  "license": "https://creativecommons.org/licenses/by/4.0/",
  "contributors": [
    {
      "type": "ORCiD",
      "url": "https://orcid.org/0009-0005-2800-4833"
    }
  ],
  "attributes": [
    {
      "pid": "PID->URL",
      "name": "URL",
      "description": "The URL of the server to which the request is to be made.",
      "obligation": "Mandatory",
      "repeatable": false
    },
    {
      "pid": "PID->HTTPMethod",
      "name": "HTTP Method",
      "description": "The HTTP method to be used for the request.",
      "obligation": "Mandatory",
      "repeatable": false
    },
    {
      "pid": "PID->HTTPHeader",
      "name": "HTTP Header",
      "description": "HTTP Header to be sent with the request.",
      "obligation": "Optional",
      "repeatable": true
    },
    {
      "pid": "PID->Cookie",
      "name": "Cookie",
      "description": "Cookie to be sent with the request.",
      "obligation": "Optional",
      "repeatable": true
    },
    {
      "pid": "PID->SessionStorage",
      "name": "Session Storage",
      "description": "Session storage variable to be sent with the request.",
      "obligation": "Optional",
      "repeatable": true
    },
    {
      "pid": "PID->RequestBody",
      "name": "Request Body",
      "description": "The body of the request.",
      "obligation": "Optional",
      "repeatable": false
    }
  ],
  "adapters": [
    "PID -> CURL",
    "PID -> JSFetchAPI",
    "PID -> JavaHTTPClient",
    "..."
  ]
}

=== maximiliani/FDConcepts/Operation Type Profiles/examples/python.json
{
  "$schema": "../schema.json",
  "pid": "PID->PythonScript",
  "name": "Python Script",
  "description": "This Operation Type Profile is used to describe how to execute a Python script.",
  "createdAt": "2024-02-05T12:00:00Z",
  "license": "https://creativecommons.org/licenses/by/4.0/",
  "contributors": [
    {
      "type": "ORCiD",
      "url": "https://orcid.org/0009-0005-2800-4833"
    }
  ],
  "adapters": [
    "PID -> PythonExec",
    "PID -> JSPyScript",
    "PID -> WASM"
  ],
  "attributes": [
    {
      "pid": "PID->URL",
      "name": "Script Location",
      "description": "The location of the Python script.",
      "obligation": "Mandatory"
    },
    {
      "pid": "PID->String",
      "name": "Entry point",
      "description": "The entry point of the Python script.",
      "obligation": "Mandatory"
    },
    {
      "pid": "PID->KVPair",
      "name": "Attribute",
      "description": "An attribute (key-value pair) to be passed to the Python script.",
      "obligation": "Optional"
    }
  ]
}
